[package]
name = "sudoku"
version = "0.1.0"
license = "GPL-3.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15"
slint = "0.2"

[build-dependencies]
slint-build = "0.2"
